spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/foodloop?currentSchema=ai,public
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/foodloop

foodloop:
  services:
    food:
      base-url: http://food:8084
    matching:
      base-url: http://matching:8087
    tenant:
      base-url: http://tenant:8083
    notification:
      base-url: http://notification:8088
  service-account:
    token-uri: http://keycloak:8080/realms/foodloop/protocol/openid-connect/token
