spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/foodloop?currentSchema=trust
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/foodloop
  kafka:
    bootstrap-servers: kafka:9092
