spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/foodloop
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      routes:
        - id: identity
          uri: http://identity:8082
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                key-resolver: "#{@rateLimitKeyResolver}"
        - id: tenant
          uri: http://tenant:8083
          predicates:
            - Path=/api/v1/organizations/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                key-resolver: "#{@rateLimitKeyResolver}"
        - id: food
          uri: http://food:8084
          predicates:
            - Path=/api/v1/food-listings/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                key-resolver: "#{@rateLimitKeyResolver}"
